disabled_rules: # rule identifiers to exclude from running
- force_try
- force_cast
- force_unwrappingitespace
- type_name
- trailing_whitespace
- identifier_name
- vertical_whitespace
- Type Body Length
- Line Length
